<%-- 
    Document   : view-member-report
    Created on : Sep 25, 2022, 12:45:01 PM
    Author     : Leo
--%>
<%@page import="com.mycompany.befit.centre.DAO.AdminDAO"%>
<%@page import="java.sql.ResultSet"%>
<%@include file="header.jsp" %>
<%@include file="sidebar.jsp" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>BEFIT Centre</title>
         <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
          <style>
            table, th, td {
  border: 1px solid grey;
  border-collapse: collapse;
  
}
th{
    color: black;
    padding: 5px;
    text-align: center; 
}
td{
    color: grey;
    font-weight:bold;
    text-align: center; 
    width: auto;
    padding: 5px;
}

h1{
    color: black;
}

h3{
    color:black;
}

button:hover{
    cursor: pointer;
}
        </style>
    </head>
    <body style="background:#dddddd;">
        <%
            String membershipID = request.getParameter("mid");
            
        %>
        
         <center><h1>Member's Report <i class="fas fa-file"></i></h1></center>
        
        <div id="display-board" style="
             position: relative; 
             color: grey;
             padding: 25px;
             justify-content: space-between;
             left: 19%;
             width: 75%;
             font-size: 17px;
             top: 35px;
             background: white;
             min-height: 65vh;
             ">
           
            <div style="display:flex; justify-content: space-between;">
            <div class="address">
                <h1>BEFIT Centre</h1>
                <p>5021 Njoro, Nakuru</p>
                <p>Tel: +254-725-564-895</p>
                <p>Email: support@befitcentre.com</p>
            </div>
        <table style="width:70%;">
            
            
            <tr style="background:#dddddd;">
                <th>Membership ID</th>
                <th>Services Taken</th>
                <th>My Plans(Upto)</th>
                <th>Address</th>
                <th>Charge</th>
                <th>Attendance Count</th>
            </tr>

            <%

ResultSet rs1=dao.viewMemberByMembershipId(membershipID);
while(rs1.next())
{
%>
<tr style="text-align: center;">
	<td><%=rs1.getString(1) %></td>
	<td><%=rs1.getString(11) %></td>
	<td><%=rs1.getString(8) %></td>
	<td><%=rs1.getString(10) %></td>
	<td>$ <%=rs1.getString(12) %></td>
	<td><%=rs1.getString(14) %></td>
        </table>
        </div>
          <br>
        <div style="border:1px solid; padding: 15px; text-align: center; width: 67.1%; margin-left:30.1%">
            <h3>Last Payment Done: <%=rs1.getString(12) %></h3><br>
            <p><i>Member Since: <%=rs1.getString(7) %></i></p>
                    
                    </div>`
                
        <br>
        <div class="member-status" style="display:flex; justify-content: space-between;">
            <div class="status">
                <p><h3>Member <%=rs1.getString(2)%>  <%=rs1.getString(3)%></h3></p>
            <p><h3>Membership is currently <%=rs1.getString(13)%>! </h3></p>
            <p>On behalf of the whole team,<br> thank you for choosing our services.</p>
            </div>
            
            <div class="approval">
                <h3>Approved By:</h3>
                <img src="images/BEFIT.png" width="150" height="150" alt="alt" style="border-radius:50%;"/>
                <p>Note: AutoGenerated</p>
            </div>
        </div>
            
            <%
}
%>
<center><button type="submit" style="padding:9px; background: #cc0000; outline: none; border: none; color: white; 
                margin-top: 1%; width: 100px;"><i class="fas fa-print"></i> Print</button></center>
       </div>
       
       
        
    </body>
</html>
