<%-- 
    Document   : view-progress-report
    Created on : Sep 26, 2022, 9:46:12 AM
    Author     : Leo
--%>
<%@page import="java.util.Date"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@page import="com.mycompany.befit.centre.DAO.AdminDAO"%>
<%@page import="java.sql.ResultSet"%>
<%@include file="header.jsp" %>
<%@include file="sidebar.jsp" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>BEFIT Centre</title>
        
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
          <style>
            table, th, td {
  border: 1px solid grey;
  border-collapse: collapse;
  
}
th{
    color: black;
    padding: 5px;
    text-align: center; 
}
td{
    color: grey;
    font-weight:bold;
    text-align: center; 
    width: auto;
    padding: 5px;
}

h1{
    color: black;
}

h3{
    color:black;
}

button:hover{
    cursor: pointer;
}
        </style>
    </head>
    <body style="background:#dddddd;">
        <%
            String membershipID = request.getParameter("mid");
            
        %>
        
         <center><h1>Progress Report <i class="fas fa-file"></i></h1></center>
        
        <div id="display-board" style="
             position: relative; 
             color: grey;
             padding: 25px;
             justify-content: space-between;
             left: 19%;
             width: 75%;
             font-size: 17px;
             top: 35px;
             background: white;
             min-height: 65vh;
             ">
           
            <div style="display:flex; justify-content: space-between;">
            <div class="address">
                <h1>BEFIT Centre</h1>
                <p>5021 Njoro, Nakuru</p>
                <p>Tel: +254-725-564-895</p>
                <p>Email: support@befitcentre.com</p>
            </div>
        <table style="width:70%;">
            
            
            <tr style="background:#dddddd;">
                <th>Membership ID</th>
                <th>Service</th>
                <th>My Plans(Upto)</th>
                <th>Initial Weight</th>
                <th>Current Weight</th>
               
            </tr>

            <%

ResultSet rs1=dao.viewMemberByMembershipId(membershipID);
while(rs1.next())
{
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
            Date date = new Date();  
        String dor=formatter.format(date);
    
    float initial_weight = rs1.getInt(15);
    float curr_weight = rs1.getInt(16);
    
    float weight_difference = curr_weight - initial_weight;
    float weight_variation = (weight_difference/initial_weight) * 100;
  
%>
<tr style="text-align: center;">
	<td><%=rs1.getString(1) %></td>
	<td><%=rs1.getString(11) %></td>
        <td><%=rs1.getString(8) %></td>
	<td><%=rs1.getInt(15) %></td>
	<td><%=rs1.getInt(16) %></td>
	
        </table>
        </div>
          <br>
        <div style="border:1px solid; padding: 15px; text-align: center; width: 67.1%; margin-left:30.1%; ">
           
            <p style="color: black;"><%=rs1.getString(2)%>  <%=rs1.getString(3)%>'s body structure started as 
                <%=rs1.getString(17) %> and now is <%=rs1.getString(18) %>. <br>
               
                The Total Weight Difference is <%out.println(weight_difference);%>KG as per the records of 
                
                <%out.println(dor);%> </p><br>
            
                    
                    </div>`
                
        <br>
        <div class="member-status" style="display:flex; justify-content: space-between;">
            <div class="status">
                <p style='color:black;'><strong>Gym Member <%=rs1.getString(2)%>  <%=rs1.getString(3)%></strong></p>
                <p style="color:black;"><strong>Weight Variation of <i style="color:green;"><%out.println(weight_variation);%>%
                        </i> as per current updates!</strong></p>
            <p>On behalf of the whole team,<br> thank you for choosing our services.</p>
            </div>
            
            <div class="approval">
                <h3>Approved By:</h3>
                <img src="images/BEFIT.png" width="150" height="150" alt="alt" style="border-radius:50%;"/>
                <p>Note: AutoGenerated</p>
            </div>
        </div>
            
            <%
}
%>
<center><button type="submit" style="padding:9px; background: #cc0000; outline: none; 
                border: none; color: white; margin-top: 1%; width: 100px;"><i class="fas fa-print"></i> 
        Print</button></center>
       </div>
    
    <body>
        
        
        
    </body>
</html>
